import type { Account } from "./types";

// 20 synthetic accounts. field values per spec; evidence lines and missing
// persona angles authored in the same terse mono style. no real HVAC brands.

export const ACCOUNTS: Account[] = [
  {
    slug: "kestrel-thermal",
    name: "Kestrel Thermal Systems",
    hq: "Tulsa, OK",
    founded: 1987,
    employees: "320–400",
    revenueBand: "$80M–$120M",
    segment: "commercial rooftop units",
    products: "packaged RTUs 3–50 ton, curbs, economizers, BAS integration kits",
    skuCount: 1400,
    dealerCount: 210,
    distribution: "2-step: reps → distributors → mechanical contractors",
    source: "AHR Expo 2026 exhibitor list",
    scores: { dealerNetwork: 88, skuComplexity: 82, supportPain: 78, docDepth: 85, whitespace: 72, revenueFit: 90 },
    evidence: {
      dealerNetwork: "210 dealers across 38 states per HARDI listing",
      skuComplexity: "1400 skus; RTU configs span 3–50 ton with curb and economizer options",
      supportPain: "3 senior techs answer the same curb-adapter fitment questions daily",
      docDepth: "40+ IOM manuals published on site, legacy models included",
      whitespace: "no chat on site; dealer portal is a pdf library",
      revenueFit: "$80M–$120M band; center of the $60K+ ACV sweet spot",
    },
    committee: [
      { id: "dana-whitfield", name: "Dana Whitfield", title: "VP Sales", angle: "dealer quote turnaround is the #1 complaint in her channel" },
      { id: "marcus-ohler", name: "Marcus Ohler", title: "Director of Dealer Operations", angle: "counter staff take 6+ months to ramp on the configurator" },
      { id: "priya-raghavan", name: "Priya Raghavan", title: "Technical Support Manager", angle: "3 senior techs answer the same curb-adapter fitment questions daily" },
    ],
    notes: "publishes 40+ IOM manuals publicly; no chat on site; dealer portal is a PDF library.",
  },
  {
    slug: "blue-ridge-hydronics",
    name: "Blue Ridge Hydronics",
    hq: "Asheville, NC",
    founded: 1974,
    employees: "150–200",
    revenueBand: "$35M–$55M",
    segment: "hydronic boilers",
    products: "condensing boilers, cast-iron commercial boilers, venting kits, controls",
    skuCount: 900,
    dealerCount: 160,
    distribution: "wholesale distributors → hydronic contractors",
    source: "AHRI member directory",
    scores: { dealerNetwork: 74, skuComplexity: 76, supportPain: 84, docDepth: 88, whitespace: 80, revenueFit: 78 },
    evidence: {
      dealerNetwork: "160 wholesale distributors per AHRI directory cross-reference",
      skuComplexity: "900 skus; venting kit compatibility varies by boiler generation",
      supportPain: "winter no-heat calls swamp the desk; error-code lookups eat the team",
      docDepth: "manual library reaches back to 1998 legacy models, all public",
      whitespace: "support line closes 5pm ET; contractors work later. no chat, no portal",
      revenueFit: "$35M–$55M band; solid mid-size fit for $60K+ ACV",
    },
    committee: [
      { id: "tom-kessler", name: "Tom Kessler", title: "VP Sales", angle: "distributors defect to whichever line answers fastest during heating season" },
      { id: "renee-alvarado", name: "Renee Alvarado", title: "Head of Technical Services", angle: "winter no-heat calls swamp the desk; error-code lookups eat her team" },
      { id: "gil-mancini", name: "Gil Mancini", title: "Aftermarket & Parts Director", angle: "wrong-part returns on venting kits run ~9%" },
    ],
    notes: "deep manual library incl. legacy models back to 1998; support line closes 5pm ET, contractors work later.",
  },
  {
    slug: "meridian-air",
    name: "Meridian Air Technologies",
    hq: "Phoenix, AZ",
    founded: 2003,
    employees: "400–500",
    revenueBand: "$120M–$180M",
    segment: "VRF & commercial heat pumps",
    products: "VRF outdoor/indoor units, branch controllers, line-set accessories, commissioning tools",
    skuCount: 2100,
    dealerCount: 240,
    distribution: "certified dealer program, direct-to-mechanical",
    source: "AHR Expo 2026 exhibitor list",
    scores: { dealerNetwork: 90, skuComplexity: 94, supportPain: 82, docDepth: 70, whitespace: 55, revenueFit: 92 },
    evidence: {
      dealerNetwork: "240 certified dealers; activation gated by a certification backlog",
      skuComplexity: "2100 skus; VRF compatibility matrix is the deepest on the list",
      supportPain: "compatibility questions across 2100 skus are the desk's daily grind",
      docDepth: "docs exist but the compat matrix lives in a 2019 excel export",
      whitespace: "already runs a portal and an FAQ-only chatbot; both weak, neither grounded",
      revenueFit: "$120M–$180M band; largest revenue on the list",
    },
    committee: [
      { id: "alex-duran", name: "Alex Duran", title: "VP Sales", angle: "dealer activation rate is the growth bottleneck he answers for every quarter" },
      { id: "keiko-tanabe", name: "Keiko Tanabe", title: "Director, Dealer Enablement", angle: "certification course backlog is gating new dealer activation" },
      { id: "sam-whitaker", name: "Sam Whitaker", title: "Technical Support Manager", angle: "compatibility matrix questions across 2100 skus bury his desk" },
      { id: "lena-ford", name: "Lena Ford", title: "Head of Digital", angle: "owns a portal contractors barely log into" },
    ],
    notes: "compatibility matrix across 2100 SKUs is the support desk's daily grind; already has a weak chatbot (FAQ-only).",
  },
  {
    slug: "vulcan-process",
    name: "Vulcan Process Heating",
    hq: "Pittsburgh, PA",
    founded: 1969,
    employees: "220–280",
    revenueBand: "$60M–$90M",
    segment: "industrial process heaters",
    products: "immersion heaters, circulation heaters, control panels, custom-engineered systems",
    skuCount: 700,
    dealerCount: 60,
    distribution: "direct + manufacturer reps",
    source: "ACHR News industrial coverage",
    scores: { dealerNetwork: 45, skuComplexity: 88, supportPain: 90, docDepth: 82, whitespace: 85, revenueFit: 84 },
    evidence: {
      dealerNetwork: "60 reps, mostly direct; channel reach is thin by design",
      skuComplexity: "700 catalog skus plus engineered-to-order; every quote needs an expert",
      supportPain: "applications engineers spend half their week on pre-sales sizing questions",
      docDepth: "wattage and watt-density guides published; sizing tables run deep",
      whitespace: "no digital pre-sales surface at all; inbound goes straight to engineers",
      revenueFit: "$60M–$90M band; engineered products support premium ACV",
    },
    committee: [
      { id: "ed-brancato", name: "Ed Brancato", title: "VP Sales", angle: "sales cycle stalls whenever a quote waits on applications engineering" },
      { id: "ana-kovacs", name: "Dr. Ana Kovács", title: "Applications Engineering Lead", angle: "her engineers spend half their week on pre-sales sizing questions" },
      { id: "ray-delgado", name: "Ray Delgado", title: "Service Manager", angle: "field techs escalate panel and wiring questions the manuals already answer" },
    ],
    notes: "engineered-to-order means every quote needs an expert; wattage/watt-density sizing questions dominate inbound.",
  },
  {
    slug: "northstar-radiant",
    name: "NorthStar Radiant",
    hq: "Minneapolis, MN",
    founded: 1991,
    employees: "120–160",
    revenueBand: "$25M–$40M",
    segment: "radiant tube & infrared heaters",
    products: "gas-fired tube heaters, high-intensity infrared, garage/warehouse kits",
    skuCount: 450,
    dealerCount: 140,
    distribution: "2-step wholesale",
    source: "AHRI member directory",
    scores: { dealerNetwork: 70, skuComplexity: 58, supportPain: 72, docDepth: 76, whitespace: 82, revenueFit: 66 },
    evidence: {
      dealerNetwork: "140 wholesale dealers per AHRI cross-reference",
      skuComplexity: "450 skus; kit configurations moderate, clearances add nuance",
      supportPain: "clearance-to-combustibles questions are 30% of calls",
      docDepth: "install manuals with clearance tables public for full catalog",
      whitespace: "no chat, no portal; seasonal spike hits a phone line",
      revenueFit: "$25M–$40M band; lower edge of the ACV sweet spot",
    },
    committee: [
      { id: "carrie-lindqvist", name: "Carrie Lindqvist", title: "VP Sales & Marketing", angle: "loses winter deals when dealers can't answer clearance questions at the counter" },
      { id: "doug-feeney", name: "Doug Feeney", title: "Technical Support Lead", angle: "clearance-to-combustibles questions are 30% of calls" },
      { id: "matt-osei", name: "Matt Osei", title: "Dealer Development Manager", angle: "recruiting dealers is easy; making them competent on 450 skus isn't" },
    ],
    notes: "strong seasonal spike Oct–Jan; support desk drowns exactly when dealers sell hardest.",
  },
  {
    slug: "cascade-chiller",
    name: "Cascade Chiller Works",
    hq: "Portland, OR",
    founded: 1998,
    employees: "260–320",
    revenueBand: "$70M–$110M",
    segment: "air- and water-cooled chillers",
    products: "scroll/screw chillers 20–500 ton, free-cooling options, plant controls",
    skuCount: 1100,
    dealerCount: 90,
    distribution: "reps + national accounts",
    source: "AHR Expo 2026 exhibitor list",
    scores: { dealerNetwork: 62, skuComplexity: 86, supportPain: 76, docDepth: 80, whitespace: 68, revenueFit: 88 },
    evidence: {
      dealerNetwork: "90 reps and national accounts; concentrated, high-value channel",
      skuComplexity: "1100 skus across 20–500 ton with free-cooling and controls options",
      supportPain: "BAS integration questions bounce between three teams",
      docDepth: "selection data and controls docs published; deep but scattered",
      whitespace: "selection software is desktop-only and 9 years old; reps quote from spreadsheets",
      revenueFit: "$70M–$110M band; chiller ACVs clear $60K easily",
    },
    committee: [
      { id: "victor-chen", name: "Victor Chen", title: "VP Sales", angle: "reps quote from 9-year-old desktop software and spreadsheets" },
      { id: "ingrid-halvorsen", name: "Ingrid Halvorsen", title: "Director of Service Operations", angle: "service escalations recycle answers that already sit in the controls docs" },
      { id: "paulo-ribeiro", name: "Paulo Ribeiro", title: "Controls Product Manager", angle: "BAS integration questions bounce between three teams" },
    ],
    notes: "selection software is desktop-only and 9 years old; reps quote from spreadsheets.",
  },
  {
    slug: "ironline-unit",
    name: "Ironline Unit Heaters",
    hq: "Cleveland, OH",
    founded: 1958,
    employees: "90–130",
    revenueBand: "$20M–$32M",
    segment: "gas unit heaters",
    products: "power-vented and separated-combustion unit heaters, thermostats, hanging kits",
    skuCount: 380,
    dealerCount: 190,
    distribution: "wholesale distribution",
    source: "HARDI distributor network mapping",
    scores: { dealerNetwork: 80, skuComplexity: 44, supportPain: 60, docDepth: 72, whitespace: 88, revenueFit: 58 },
    evidence: {
      dealerNetwork: "190 distributors per HARDI network mapping",
      skuComplexity: "380 skus; simple line, venting options add the only depth",
      supportPain: "small desk covers 190 distributors with no self-serve layer",
      docDepth: "install and venting manuals public for the whole line",
      whitespace: "no digital surface at all beyond a brochure site",
      revenueFit: "$20M–$32M band; below sweet spot, lean family-owned team",
    },
    committee: [
      { id: "hank-willoughby", name: "Hank Willoughby", title: "President & VP Sales", angle: "wears both hats; wants dealers self-serving basic questions" },
      { id: "joan-marek", name: "Joan Marek", title: "Customer Service Manager", angle: "her 3-person desk covers 190 distributors with no self-serve layer" },
      { id: "terrell-boone", name: "Terrell Boone", title: "Regional Sales Manager", angle: "counter staff who can't answer venting questions spec a competitor instead" },
    ],
    notes: "family-owned, lean team; no digital surface at all beyond a brochure site.",
  },
  {
    slug: "gulfstream-dehum",
    name: "Gulfstream Dehumidification",
    hq: "Tampa, FL",
    founded: 2008,
    employees: "110–150",
    revenueBand: "$28M–$45M",
    segment: "commercial dehumidifiers",
    products: "pool dehumidifiers, DOAS units, corrosion-resistant coastal packages",
    skuCount: 520,
    dealerCount: 85,
    distribution: "reps → mechanical contractors, natatorium specialists",
    source: "AHR Expo 2026 exhibitor list",
    scores: { dealerNetwork: 55, skuComplexity: 68, supportPain: 80, docDepth: 74, whitespace: 78, revenueFit: 70 },
    evidence: {
      dealerNetwork: "85 reps and natatorium specialists; narrow, expert channel",
      skuComplexity: "520 skus; coastal packages and DOAS options complicate selection",
      supportPain: "pool-room sizing mistakes cause warranty fights",
      docDepth: "sizing and application guides public; natatorium know-how is not",
      whitespace: "no chat or portal; niche expertise lives in 2 people's heads, both near retirement",
      revenueFit: "$28M–$45M band; niche premium supports mid ACV",
    },
    committee: [
      { id: "marisol-vega", name: "Marisol Vega", title: "VP Sales", angle: "warranty fights from sizing mistakes eat margin and goodwill" },
      { id: "chip-landry", name: "Chip Landry", title: "Applications Manager", angle: "pool-room sizing mistakes cause warranty fights" },
      { id: "erin-dvorak", name: "Erin Dvorak", title: "Marketing Manager", angle: "spec-page traffic converts nothing; no way to capture the engineer who lands there" },
    ],
    notes: "niche expertise (natatoriums) lives in 2 people's heads; both near retirement.",
  },
  {
    slug: "prairie-furnace",
    name: "Prairie Furnace Co",
    hq: "Wichita, KS",
    founded: 1963,
    employees: "200–260",
    revenueBand: "$50M–$75M",
    segment: "commercial furnaces & make-up air",
    products: "direct/indirect-fired MUA, duct furnaces, kitchen ventilation heat",
    skuCount: 640,
    dealerCount: 175,
    distribution: "2-step wholesale",
    source: "HARDI distributor network mapping",
    scores: { dealerNetwork: 78, skuComplexity: 62, supportPain: 70, docDepth: 78, whitespace: 84, revenueFit: 74 },
    evidence: {
      dealerNetwork: "175 distributors per HARDI network mapping",
      skuComplexity: "640 skus; MUA sizing requires airflow math most counters can't do",
      supportPain: "sizing questions stack up at the desk every morning",
      docDepth: "MUA sizing guides and duct furnace manuals public",
      whitespace: "no digital spec tools; distributors carry 4 competing lines",
      revenueFit: "$50M–$75M band; comfortable mid-size fit",
    },
    committee: [
      { id: "gordon-pike", name: "Gordon Pike", title: "VP Sales", angle: "whichever line is easiest to spec wins the distributor's counter" },
      { id: "althea-bryant", name: "Althea Bryant", title: "Technical Services Director", angle: "MUA airflow questions stack up at her desk every morning" },
      { id: "russ-kimble", name: "Russ Kimble", title: "Distributor Relations Manager", angle: "distributors carry 4 competing lines; whoever is easiest to spec wins" },
    ],
    notes: "MUA sizing questions require airflow math most counter staff can't do.",
  },
  {
    slug: "summit-erv",
    name: "Summit ERV Systems",
    hq: "Denver, CO",
    founded: 2011,
    employees: "80–110",
    revenueBand: "$18M–$30M",
    segment: "energy recovery ventilators",
    products: "ERV/HRV cores, packaged rooftop ERVs, controls",
    skuCount: 340,
    dealerCount: 70,
    distribution: "reps + direct to design-build",
    source: "AHR Expo 2026 exhibitor list",
    scores: { dealerNetwork: 48, skuComplexity: 60, supportPain: 64, docDepth: 70, whitespace: 76, revenueFit: 60 },
    evidence: {
      dealerNetwork: "70 reps plus direct design-build relationships",
      skuComplexity: "340 skus; core sizing and controls pairing carry the nuance",
      supportPain: "code questions (ASHRAE 62.1) repeat in every design-build meeting",
      docDepth: "application guides tied to code requirements, publicly posted",
      whitespace: "no digital education layer; buyers arrive confused",
      revenueFit: "$18M–$30M band; below sweet spot, education-heavy sale",
    },
    committee: [
      { id: "nia-okafor", name: "Nia Okafor", title: "VP Sales & Co-founder", angle: "buyers arrive confused by ASHRAE 62.1; education is the sale" },
      { id: "brett-halloran", name: "Brett Halloran", title: "Applications Engineer", angle: "answers the same code questions in every design-build meeting" },
      { id: "sofia-marchetti", name: "Sofia Marchetti", title: "Operations Manager", angle: "quote turnaround slips whenever engineering gets pulled into pre-sales" },
    ],
    notes: "code-driven demand (ASHRAE 62.1) means buyers arrive confused; education is the sale.",
  },
  {
    slug: "halcyon-cooling",
    name: "Halcyon Cooling Towers",
    hq: "Baltimore, MD",
    founded: 1982,
    employees: "240–300",
    revenueBand: "$65M–$95M",
    segment: "cooling towers & fluid coolers",
    products: "FRP towers, closed-circuit coolers, fill/drift retrofit kits",
    skuCount: 800,
    dealerCount: 100,
    distribution: "reps + aftermarket parts direct",
    source: "AHRI member directory",
    scores: { dealerNetwork: 60, skuComplexity: 72, supportPain: 74, docDepth: 82, whitespace: 70, revenueFit: 82 },
    evidence: {
      dealerNetwork: "100 reps plus direct aftermarket parts channel",
      skuComplexity: "800 skus; retrofit kit fitment spans 20+ years of tower models",
      supportPain: "parts identification on 20-year-old towers is a photo-and-pray process",
      docDepth: "parts catalogs and IOM manuals public back through legacy lines",
      whitespace: "no parts-lookup tool; aftermarket runs on emailed photos",
      revenueFit: "$65M–$95M band; aftermarket is 40% of revenue",
    },
    committee: [
      { id: "walt-jessup", name: "Walt Jessup", title: "VP Sales", angle: "aftermarket is 40% of revenue and it's gated on parts identification" },
      { id: "farrah-nassar", name: "Farrah Nassar", title: "Aftermarket Director", angle: "parts identification on 20-year-old towers is a photo-and-pray process" },
      { id: "omar-castellanos", name: "Omar Castellanos", title: "Service Network Manager", angle: "field crews wait days on legacy-tower parts confirmations" },
    ],
    notes: "aftermarket is 40% of revenue; parts fitment on legacy units is the pain center.",
  },
  {
    slug: "redrock-combustion",
    name: "Redrock Combustion",
    hq: "Salt Lake City, UT",
    founded: 1995,
    employees: "130–170",
    revenueBand: "$30M–$50M",
    segment: "burners & combustion controls",
    products: "gas burners, flame safeguards, retrofit kits, tuning tools",
    skuCount: 560,
    dealerCount: 120,
    distribution: "wholesale + OEM supply",
    source: "ACHR News industrial coverage",
    scores: { dealerNetwork: 66, skuComplexity: 78, supportPain: 86, docDepth: 78, whitespace: 74, revenueFit: 68 },
    evidence: {
      dealerNetwork: "120 wholesale accounts plus OEM supply relationships",
      skuComplexity: "560 skus; retrofit fitment and safeguard pairing carry real depth",
      supportPain: "commissioning support calls run 45 min average",
      docDepth: "burner manuals and tuning guides public for both audiences",
      whitespace: "two-audience docs confuse everyone; no guided answer layer",
      revenueFit: "$30M–$50M band; solid mid-size fit",
    },
    committee: [
      { id: "deb-sorenson", name: "Deb Sorenson", title: "VP Sales", angle: "OEM and wholesale buyers get the same confusing docs" },
      { id: "luis-barrientos", name: "Luis Barrientos", title: "Field Service Manager", angle: "commissioning support calls run 45 min average" },
      { id: "kenji-morita", name: "Kenji Morita", title: "OEM Accounts Manager", angle: "OEM engineers want spec answers in hours, not days" },
    ],
    notes: "sells through OEMs too; two-audience docs confuse everyone.",
  },
  {
    slug: "lakeshore-steam",
    name: "Lakeshore Steam Specialties",
    hq: "Milwaukee, WI",
    founded: 1977,
    employees: "100–140",
    revenueBand: "$22M–$36M",
    segment: "steam humidifiers & specialties",
    products: "steam humidifiers, dispersion panels, condensate gear",
    skuCount: 410,
    dealerCount: 95,
    distribution: "reps → mechanical contractors",
    source: "AHRI member directory",
    scores: { dealerNetwork: 52, skuComplexity: 64, supportPain: 72, docDepth: 80, whitespace: 80, revenueFit: 62 },
    evidence: {
      dealerNetwork: "95 reps into mechanical contractors; modest reach",
      skuComplexity: "410 skus; dispersion sizing depends on psychrometrics",
      supportPain: "psychrometrics questions stall every first-time buyer",
      docDepth: "engineering guides teach the physics; all public",
      whitespace: "no digital education layer for a physics-heavy sale",
      revenueFit: "$22M–$36M band; below sweet spot, long cycle",
    },
    committee: [
      { id: "peter-vandenberg", name: "Peter Vandenberg", title: "General Manager", angle: "the educational sales cycle stalls at the physics, every time" },
      { id: "colleen-rafferty", name: "Colleen Rafferty", title: "Technical Support Supervisor", angle: "psychrometrics questions stall every first-time buyer" },
      { id: "andre-sylvain", name: "Andre Sylvain", title: "Sales Engineer", angle: "walks every first-time buyer through the same psychrometrics 101" },
    ],
    notes: "sells physics as much as hardware; long educational sales cycle.",
  },
  {
    slug: "everline-ductless",
    name: "Everline Ductless",
    hq: "Sacramento, CA",
    founded: 2014,
    employees: "170–220",
    revenueBand: "$45M–$70M",
    segment: "ductless mini-splits (commercial/light-commercial)",
    products: "single/multi-zone systems, ceiling cassettes, line-set kits, wifi controls",
    skuCount: 980,
    dealerCount: 260,
    distribution: "certified dealer program + distribution",
    source: "AHR Expo 2026 exhibitor list",
    scores: { dealerNetwork: 92, skuComplexity: 74, supportPain: 78, docDepth: 66, whitespace: 60, revenueFit: 76 },
    evidence: {
      dealerNetwork: "260 dealers, biggest network on the list; 4 trainers total",
      skuComplexity: "980 skus; multi-zone pairing rules trip up new dealers",
      supportPain: "line-set and control pairing questions dominate call volume",
      docDepth: "manuals public but pairing rules scattered across bulletins",
      whitespace: "invests in dealer training already; no self-serve answer layer yet",
      revenueFit: "$45M–$70M band; solid fit, enablement budget exists",
    },
    committee: [
      { id: "jasmine-cho", name: "Jasmine Cho", title: "VP Sales", angle: "dealer competence caps growth, not demand" },
      { id: "robbie-muniz", name: "Robbie Muniz", title: "Dealer Program Manager", angle: "260 dealers, 4 trainers; enablement doesn't scale" },
      { id: "tara-whitcomb", name: "Tara Whitcomb", title: "Support Center Lead", angle: "line-set and control pairing questions dominate her call volume" },
      { id: "devin-okada", name: "Devin Okada", title: "E-commerce Manager", angle: "product pages answer nothing; carts stall at the compatibility step" },
    ],
    notes: "biggest dealer network on the list; already invests in dealer training, receptive to enablement tech.",
  },
  {
    slug: "foundry-hx",
    name: "Foundry Heat Exchange",
    hq: "Detroit, MI",
    founded: 1971,
    employees: "180–230",
    revenueBand: "$40M–$65M",
    segment: "heat exchangers",
    products: "plate, shell-and-tube, brazed-plate exchangers, gaskets/plates aftermarket",
    skuCount: 720,
    dealerCount: 75,
    distribution: "direct + reps",
    source: "ACHR News industrial coverage",
    scores: { dealerNetwork: 50, skuComplexity: 76, supportPain: 78, docDepth: 76, whitespace: 82, revenueFit: 72 },
    evidence: {
      dealerNetwork: "75 reps, mostly direct; thin channel by design",
      skuComplexity: "720 skus; gasket and plate fitment spans competitor units too",
      supportPain: "sizing requests queue 3 days deep",
      docDepth: "sizing tables and gasket cross-references published",
      whitespace: "no digital sizing tool; the queue is the product experience",
      revenueFit: "$40M–$65M band; aftermarket upside strengthens the case",
    },
    committee: [
      { id: "stan-wozniak", name: "Stan Wozniak", title: "VP Sales", angle: "the 3-day sizing queue costs him deals to faster-quoting rivals" },
      { id: "helena-brandt", name: "Helena Brandt", title: "Applications Engineering Manager", angle: "sizing requests queue 3 days deep" },
      { id: "curtis-long", name: "Curtis Long", title: "Aftermarket Sales Manager", angle: "gasket fitment on competitor units is lucrative and lives in 2 heads" },
    ],
    notes: "gasket/plate fitment on competitor units is a lucrative, expertise-bound aftermarket.",
  },
  {
    slug: "coastal-marine",
    name: "Coastal Marine HVAC",
    hq: "Norfolk, VA",
    founded: 1989,
    employees: "70–100",
    revenueBand: "$15M–$25M",
    segment: "marine HVAC",
    products: "self-contained marine AC, chillers for vessels, corrosion-proof ducting",
    skuCount: 290,
    dealerCount: 110,
    distribution: "boatyard dealers + marine distributors",
    source: "AHRI member directory",
    scores: { dealerNetwork: 64, skuComplexity: 56, supportPain: 76, docDepth: 62, whitespace: 84, revenueFit: 48 },
    evidence: {
      dealerNetwork: "110 boatyard dealers and marine distributors",
      skuComplexity: "290 skus; vessel constraints add selection nuance",
      supportPain: "boatyards call from the dock with the panel open",
      docDepth: "install manuals public; troubleshooting depth thinner than others here",
      whitespace: "zero digital support surface; the phone is the product",
      revenueFit: "$15M–$25M band; smallest on list, borderline ACV fit",
    },
    committee: [
      { id: "bo-trask", name: "Bo Trask", title: "Owner/VP Sales", angle: "every support call he takes personally is selling time lost" },
      { id: "yolanda-reyes", name: "Yolanda Reyes", title: "Service Coordinator", angle: "boatyards call from the dock with the panel open" },
      { id: "neil-farraday", name: "Neil Farraday", title: "Dealer Sales Rep", angle: "boatyard dealers stock whichever line is easiest to troubleshoot" },
    ],
    notes: "smallest revenue on list; borderline ACV fit, but a vivid photo-and-voice support use case.",
  },
  {
    slug: "highplains-evap",
    name: "Highplains Evaporative",
    hq: "Lubbock, TX",
    founded: 1984,
    employees: "90–120",
    revenueBand: "$19M–$30M",
    segment: "evaporative cooling",
    products: "industrial evap coolers, media, pumps, controls",
    skuCount: 330,
    dealerCount: 150,
    distribution: "wholesale distribution",
    source: "HARDI distributor network mapping",
    scores: { dealerNetwork: 72, skuComplexity: 48, supportPain: 58, docDepth: 64, whitespace: 86, revenueFit: 54 },
    evidence: {
      dealerNetwork: "150 distributors per HARDI network mapping",
      skuComplexity: "330 skus; media and pump pairing is the main depth",
      supportPain: "seasonal call spike hits with no extra headcount",
      docDepth: "manuals public but thinner than the industrial peers here",
      whitespace: "digital whitespace total; brochure site only",
      revenueFit: "$19M–$30M band; price-driven category compresses ACV",
    },
    committee: [
      { id: "wade-hollister", name: "Wade Hollister", title: "VP Sales", angle: "price-driven category; support ease is the only differentiation left" },
      { id: "consuelo-marin", name: "Consuelo Marín", title: "Customer Service Manager", angle: "seasonal call spike hits with no extra headcount" },
      { id: "judd-ferris", name: "Judd Ferris", title: "Territory Manager", angle: "counters that can't explain media choices sell on price instead" },
    ],
    notes: "seasonal, price-driven category; support pain moderate but digital whitespace total.",
  },
  {
    slug: "sterling-cleanroom",
    name: "Sterling Cleanroom Air",
    hq: "Raleigh, NC",
    founded: 2006,
    employees: "140–180",
    revenueBand: "$38M–$60M",
    segment: "cleanroom air handling",
    products: "cleanroom AHUs, fan filter units, pressure controls, validation kits",
    skuCount: 480,
    dealerCount: 55,
    distribution: "direct to pharma/semi contractors + reps",
    source: "AHR Expo 2026 exhibitor list",
    scores: { dealerNetwork: 42, skuComplexity: 80, supportPain: 82, docDepth: 84, whitespace: 66, revenueFit: 80 },
    evidence: {
      dealerNetwork: "55 reps; direct pharma/semi relationships dominate",
      skuComplexity: "480 skus; validation kit pairing and pressure specs run deep",
      supportPain: "compliance documentation requests are 8-hour jobs",
      docDepth: "validation docs and IOM manuals published; regulated buyers demand it",
      whitespace: "documentation requests handled by email, one at a time",
      revenueFit: "$38M–$60M band; regulated premium supports strong ACV",
    },
    committee: [
      { id: "mei-ling-shaw", name: "Dr. Mei-Ling Shaw", title: "VP Sales & Applications", angle: "regulated buyers want every answer cited; sales cycles die in documentation" },
      { id: "oscar-delacroix", name: "Oscar Delacroix", title: "Validation Support Lead", angle: "compliance documentation requests are 8-hour jobs" },
      { id: "hana-petrov", name: "Hana Petrov", title: "Project Engineering Manager", angle: "project submittals recycle the same validation answers" },
    ],
    notes: "regulated buyers; every answer needs a citation. Prox's cited-to-the-page pitch is literal here.",
  },
  {
    slug: "quarry-fans",
    name: "Quarry Industrial Fans",
    hq: "Louisville, KY",
    founded: 1979,
    employees: "160–210",
    revenueBand: "$42M–$68M",
    segment: "HVLS & industrial fans",
    products: "HVLS fans, exhaust/supply fans, controls, mounting systems",
    skuCount: 610,
    dealerCount: 185,
    distribution: "2-step + national accounts",
    source: "HARDI distributor network mapping",
    scores: { dealerNetwork: 82, skuComplexity: 58, supportPain: 62, docDepth: 72, whitespace: 78, revenueFit: 74 },
    evidence: {
      dealerNetwork: "185 dealers per HARDI mapping plus national accounts",
      skuComplexity: "610 skus; mounting system selection carries the depth",
      supportPain: "inside sales quotes mounting hardware wrong weekly",
      docDepth: "mounting guides with joist-load tables published",
      whitespace: "no spec tool; structural questions scare dealers off closing",
      revenueFit: "$42M–$68M band; comfortable mid-size fit",
    },
    committee: [
      { id: "reggie-calhoun", name: "Reggie Calhoun", title: "VP Sales", angle: "structural mounting fear kills deals generalist dealers should close" },
      { id: "bridget-malone", name: "Bridget Malone", title: "Inside Sales Manager", angle: "her team quotes mounting hardware wrong weekly" },
      { id: "santiago-vidal", name: "Santiago Vidal", title: "National Accounts Director", angle: "national accounts expect spec answers same-day" },
    ],
    notes: "structural mounting questions (joist loads) scare generalist dealers off closing.",
  },
  {
    slug: "beacon-snowmelt",
    name: "Beacon Snowmelt & Hydronic Controls",
    hq: "Burlington, VT",
    founded: 2001,
    employees: "60–90",
    revenueBand: "$14M–$24M",
    segment: "snowmelt & hydronic controls",
    products: "snowmelt controllers, sensors, mixing valves, zone controls",
    skuCount: 260,
    dealerCount: 130,
    distribution: "wholesale + e-commerce",
    source: "AHRI member directory",
    scores: { dealerNetwork: 68, skuComplexity: 52, supportPain: 66, docDepth: 70, whitespace: 62, revenueFit: 46 },
    evidence: {
      dealerNetwork: "130 wholesale accounts plus direct e-commerce",
      skuComplexity: "260 skus; wiring and sensor pairing carry the nuance",
      supportPain: "install-wiring photos flood the support inbox every November",
      docDepth: "wiring diagrams and install guides public for full catalog",
      whitespace: "already sells online; natural chat-widget adopter, none installed",
      revenueFit: "$14M–$24M band; smallest ACV fit on the list",
    },
    committee: [
      { id: "elliot-marsh", name: "Elliot Marsh", title: "Founder & VP Sales", angle: "small team; November install season buries everyone at once" },
      { id: "dot-kowalski", name: "Dot Kowalski", title: "Support Lead", angle: "install-wiring photos flood her inbox every November" },
      { id: "van-nguyen", name: "Van Nguyen", title: "Digital Sales Manager", angle: "sells online already; wants the site to answer wiring questions itself" },
    ],
    notes: "small but digitally curious; already sells online, natural chat-widget adopter.",
  },
];

export function getAccount(slug: string): Account | undefined {
  return ACCOUNTS.find((a) => a.slug === slug);
}
